trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'cobertura:cobertura'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    codeCoverageToolOption: 'Cobertura'
    codeCoverageFailIfEmpty: true
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    sonarQubeRunAnalysis: false
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: '(curl -s https://codecov.io/bash) -t af2b16ff-aa66-4545-8891-36be89b10be6'
